### PR TITLE
Docker metrics

### PR DESCRIPTION
**Pull request by cgswong**
Docker metric setup post

### CODE REVIEW

**Comment by jessitron** [comment]
First sentence: "For some time now, we've been using [Docker](http://www.docker.com) with it's usage growing"
should be "its" and put a comma before "with"

**Comment by jessitron** [comment]
How do I make a PR on this PR?

**Comment by cgswong** [comment]
@jessitron Corrected the typo, thanks.

**Comment by slbahr** [comment]
Looks good!  I especially like the graphics\dashboards on this one.  Ryan and/or David..Please approve and this will be ready to be published.

**Comment by ddgenome** [comment]
@cgswong , this looks really good, more thorough than other stuff out there. I forked your repo, fixed up the formatting, reworked a bit of the text and issued a pull request against your fork.

**Comment by cgswong** [comment]
@ddgenome Your PR has been merged, thanks! I also made a grammar correction as well.

**Comment by ddgenome** [comment]
@cgswong two things I forgot to mention:

1.  Could you come up with a subtitle that is different than title? Something like "Tutorial for creating Docker metrics dashboards"
2.  Can you add a "tutorials" tag?

Also, it looks like the PR is messed up somehow because now the post appears under both the old name/date and the name/date. Is it like that in your repo too? Can you remove the old one?

**Comment by cgswong** [comment]
@ddgenome Suggested changes have been made.

**Comment by ddgenome** [comment]
Seems at least one of my formatting changes, line breaks in Grafana step 2, got lost somehow. I'll merge this in a make that correction.

**Pull request merged**
