### PR TITLE
Post about using jq to change JSON

### PR DESCRIPTION
**Pull request by jessitron**

### CODE REVIEW

**Comment by jessitron** [comment]
thank you autocorrect :-(

**Comment by slbahr** [comment]
Jessica....Looks good but I would like Ryan Richt to review as well before I officially approve.  :-)  I love that you have only been here a few weeks and already looking at how to contribute to this too!  Look forward to meeting you in person.

**Comment by ddgenome** [comment]
It looks good to me. I made a couple minor changes.

**Comment by ddgenome** [comment]
Actually, the update script we have works from develop, not master, so I am going to close this PR and issue another one to develop.

**Comment by jessitron** [comment]
dangit! did you change the default branch then?

**Comment by ddgenome** [comment]
Yes, I changed the default branch to develop

**Comment by ddgenome** [comment]
I'm also trying to improve the script.

**Pull request closed without merging**
