### PR TITLE
Blog post to kick-off multipart CF project releases

### PR DESCRIPTION
**Pull request by mjseid**

### CODE REVIEW

**Comment by slbahr** [comment]
I like it and I really like how you laid out the 3 parts for them to look forward to.  Is there anything that will go along with each posting from a blogging perspective?  @ddgenome and @ryan-richt ..thoughts?

**Comment by ryan-richt** [comment]
Looks good, please capitalize "Monsanto" and I'd replace "/" in last sentence with "and"

**Comment by mjseid** [comment]
Thanks, updates made. 

I planned on making a small blog post to go with each of the 3 projects in addition to this kick-off one

**Comment by slbahr** [comment]
Thanks @mjseid .  I like where you are going with this and will be scheduling some time with you as I would like to see some things on a regular basis and pull together a schedule for FY16 planned posts.  I would like to include you as a larger part of helping us figure out what that might look like.

**Comment by ddgenome** [comment]
Looks like this one is good to go. I'll merge and get it posted.

**Comment by ddgenome** [comment]
May have moved too soon here. Only cf-portal is open source, but the post has links to two private repos, which will resolve to 404s for people not in MonsantoCo.

**Comment by ddgenome** [comment]
I'll just remove the bullets, add a link to cf-portal in the previous paragraph and publish.

**Comment by mjseid** [comment]
OK, I was going to leave the bullets and add the links as the projects get released.  I'll change it to that format when the cfportal post pr gets sent.

Thanks for fixing it in the interim

--- Original Message ---

**Pull request merged**
