### PR TITLE
CFTG Post

### PR DESCRIPTION
**Pull request by ryan-richt**
Not ready for prime time yet, but here's a PR to track reviews. Comments/Edits welcome!

### CODE REVIEW

**Comment by ryan-richt** [comment]
@ddgenome @hibikir mind to take a look?

**Comment by slbahr** [comment]
I like the post and how you summarized.  The one part I paused is where you said "so I lied".  Not that I did not see the humor in this, I did!  Just not sure how others will see it associated with monsanto.

**Comment by ddgenome** [comment]
We should not merge this PR. The `update_prod.sh` handles merging into master and publishing to gh-pages.

**Comment by ddgenome** [comment]
I am going to close the PR, move the post to a branch, and open a new PR.

**Pull request closed without merging**
