### PR TITLE
Add algebraic data type post.

### PR DESCRIPTION
**Pull request by jfklingler**

### CODE REVIEW

**Comment by tj-corrigan** [comment]
The code in your example project should be moved under the monsantoco account. Please go through the moseg process (https://github.com/MonsantoCo/moseg).

**Comment by tj-corrigan** [comment]
might also throw a link to `https://en.wikipedia.org/wiki/Fizz_buzz` for those people like myself who forgot about the game

**Comment by slbahr** [comment]
I like the blog but a couple of minor correction:
*  Correct spelling of 'opportunites' to 'opportunities' - We've defined Fizz, Buzz, FizzBuzz, and JustInt. It might not be clear yet why we've defined constructor arguments for Fizz, Buzz , and FizzBuzz, but it gives us some opportunities that we'll talk about in a minute.

**Comment by jfklingler** [comment]
Thanks for reviewing. I've made the changes you requested and created a new OS request in moseg for the companion code: https://github.com/MonsantoCo/moseg/issues/39. I've also deleted my personal repo that was originally referenced.

**Comment by slbahr** [comment]
Approved...pending my approval of the Moseg code.

**Comment by tj-corrigan** [comment]
@slbahr we are good on the code, do we need to do anything else for the blog?

**Comment by tj-corrigan** [comment]
I have merged this in manually since we had to trim some history.

**Comment by tj-corrigan** [comment]
@jfklingler go ahead and delete your branch when you get a chance

**Pull request closed without merging**
