### PR TITLE
New Careers page on this blog

### PR DESCRIPTION
**Pull request by pjcras**
This pull request has the below changes 
1. finalized text from HR
2. link to the new recruiting video
3. new search button to launch the it-engineering jobs on the portal using the vanity url

### CODE REVIEW

**Comment by pjcras** [comment]
@tj-corrigan @slbahr The changes for the careers page on the engineering blog are completed. You can merge the same in the main develop branch and deploy. Please let me know if you see any issues.

Thanks, Prasanna

**Comment by tj-corrigan** [comment]
I just rendered it on my local machine at it looks good. What is the `_data/jobs.json` file?

**Comment by pjcras** [comment]
oops this was the original approach then we decided to go linking to the jobs portal. I will remove this file and create another PR

**Comment by pjcras** [comment]
@tj-corrigan I have removed this file now, can you update the pull request again?

**Comment by pjcras** [comment]
@tj-corrigan The vanity url that I was given was incorrect. Using a new vanity URL and all should be good now. Can you please pull all the latest changes and see it all looks good at your end. Note: with the new change when you hit the search button it should bring up the IT jobs currently open.

@slbahr can you please approve this change once the pull request is accepted.

Thanks, Prasanna

**Comment by slbahr** [comment]
Approved

**Comment by tj-corrigan** [comment]
changes should be live

**Comment by pjcras** [comment]
Yep, it is. Thanks so much

**Pull request merged**
