### PR TITLE
is that it: added post about using big data for good

### PR DESCRIPTION
**Pull request by ddgenome**
This time the pull request is into the correct branch, develop. Please review. Thanks!

### CODE REVIEW

**Comment by slbahr** [comment]
I like it but have a few comments/questions before we post:  1.)  Can we change the title?  'Is that it' does not really draw me to the article.  I like the overall concept of the article and it makes sense to me.  Just want us to draw then reader in further.  2.)  You mention your previous work history and I have no issue with comments on that except is there anything you are stating there that is considered confidential or that they would be concerned with you comment or stating what they are doing?  3.)  Because this article is not only Techie based I will be asking someone from communications to weigh in and ask for a fast turn around on response.

**Comment by timwilliate** [comment]
I feel like the post as a written is a good first part of what could be a fantastic longer post. It seems like it is missing a concrete intellectual contribution to the community about how precisely Monsanto is leveraging "Big Data" in the genomics space. What about collaborating with Rob Long to add the story about the backend of GenRe? That is a great example, that has meaningful lessons to readers, and Rob has already given this talk public and had all the material vetted. At the very minimum maybe include a link to where StampedeCon posted Rob's talk.

I really do think what is written is good, I just think that if it were taken farther, it would be a really nice article that would get read...rather than just browsed.

**Comment by ddgenome** [comment]
@slbahr: 1. I am open to changing the title. I actually took the title from Bob Geldof's autobiography. 2. There are no concerns about any references to my prior work. Everything I mention has long been public. 3. I saw the email, looks like this might get pulled to another venue.

@timwilliate: My main concern was that the post was too long. Perhaps if this more intentionally generic content gets moved to a different venue, we could build on it to create the post you recommend.

**Comment by slbahr** [comment]
Thanks David!  1.)  Lets look for another title.  Why not use your subtitle?  Or we can use something like "Using Big Data to Drive new opportunities in Agriculture"?  Thoughts?

Tim..I like the idea but would recommend that we push it out and have a separate blog or additional information that includes the genomics space.  I like the concept but if we wait then 1.) we may miss an opportunities on providing a series of articles on our big data opportunities.  Thus missing our blogging opportunities.  2.)  We take too long with getting these blogs out.

**Comment by timwilliate** [comment]
@ddgenome I actually think a long article is a good thing. By far, some of the of the best tech blog articles that I have ever read are those written by Jay Kreps and his collaborators. Each one of those articles translates to several pages. However, everyone that I read I save in Evernote, marking up, and constantly re-reading. Every article teaches me something about the technology that I would never have sought out on my own, but am grateful for having read.

I think that this is a chance for you to create an article that people keep and reference, rather they just browse through in an RSS reader. We should be using every opportunity to expose readers to what we actually build.

**Comment by timwilliate** [comment]
@slbahr The very best engineering blogs in my list of feeds almost always favor long form content over short posts, or at the very minimum there is a good mix.

However, I do understand your point about getting content out faster.

@ddgenome At the very minimum, could you at least link to the published talk that @arrogantrobot gave at StampedeCon? That would provide an example of somethings that Monsanto has done in the space which you are highlighting, and it would also recirculate some of the (at this point) rare times that we have spoken publicly about what we build. That would increase the content of the post with almost no additional length.

**Comment by slbahr** [comment]
I like the inclusion of the link to the Stampedcon talk.  David please take note of Kate's feedback but I will tell you I like how you started it out and would be fine with leaving it as you had it.  In regards to the Title, I still would like to see that change.  Do you want to update once more and then send to me for final approval?  I would like you to post this today if possible.  Thoughts?

**Comment by ddgenome** [comment]
@timwilliate I found the SlideShare of the talk. Is that what you want linked or is there a video? http://www.slideshare.net/StampedeCon/managing-genomes-at-scale-what-we-learned-stampedecon-2014

**Comment by slbahr** [comment]
I don't recall a video only a slideshare from the event.  Per your email please update the title as well.  Suggested title: Using Big Data for Good Suggested Subtitle: Big Data, it's not just for selling ads anymore

**Comment by timwilliate** [comment]
@ddgenome @slbahr There was only the SlideShare, which you found. I got confused because the organizer mentioned making videos of the talks to be presented this current year.

**Comment by ddgenome** [comment]
@slbahr I've made the updates. @timwilliate I added some text and embedded the SlideShare. In an email thread we decided to use this post as a primer and follow with more detailed content, similar to other engineering blogs that include both technical and cultural posts. I chatted with Rob and he is planning on making a post next month.

Are we set to go?

**Comment by timwilliate** [comment]
@ddgenome I think this is a post that will be great to actively share around Twitter (as long as we are okay with now advertising the blog). It provides great background into the domain we live in, and the problems we solve. I think it will get some great press.

**Comment by ddgenome** [comment]
@timwilliate yes, we are free and encouraged to share this blog. Thanks.

**Comment by slbahr** [comment]
Approved...Please post

**Pull request merged**
