### PR TITLE
added a new careers page with a sample jobs.json data

### PR DESCRIPTION
**Pull request by pjcras**
This is the first cut at the proposed careers page. It uses a local jobs.json which can be manually edited to get the jobs listing updated on the blog. The current listings in the jobs.json is mocked up. 

This pull request is for review purpose only and to identify if any changes are desired, please do not merge and release it yet as we have to wait on David Carter/ Stephanie Bahr with the go ahead for releasing this feature.

### CODE REVIEW

**Comment by tj-corrigan** [comment]
@slbahr pinging you in case you hadn't seen this

**Comment by slbahr** [comment]
Thanks TJ!  I think we are waiting on a few minor modifications based on feedback from HR.  I will forward part of that email trail to you, Mark and Tyler so you can see what is transpiring on that end.

**Comment by slbahr** [comment]
@pjcras - Can you check with Dave Carter on what additional changes are required by HR prior to this going live?

**Comment by pjcras** [comment]
@slbahr I contacted Dave Carter he said he hasn't heard from HR yet. He was going to follow up again and let me know accordingly. Will keep you updated.

**Comment by pjcras** [comment]
we have a new approach now to launching the jobs page. so closing this pull request

**Pull request closed without merging**
