### PR TITLE
Cloud Different post for re:Invent

### PR DESCRIPTION
**Pull request by ddgenome**
It would be great if we could get this out today. Thanks @slbahr !

### CODE REVIEW

**Comment by chrisshafer** [comment]
Just an FYI, once https://github.com/MonsantoCo/engineering-blog/pull/46 is merged the format for authors will change, see https://github.com/MonsantoCo/engineering-blog/pull/46/files#diff-c0f0f5aff7bd3d6f42d2b39bdb1bd63e for an example.

**Comment by ddgenome** [comment]
@chrisshafer does it need to change for individual authors or only when there are multiple authors?

**Comment by slbahr** [comment]
Looks good...post @ddgenome

**Comment by chrisshafer** [comment]
@ddgenome  It changed for both. Originally I wrote it support the old data model as well as the new one, but I figured it would be easier to migrate it now than to support multiple models. 

No need to worry about it till the change is merged, I just want to make sure people are aware of it.

**Pull request merged**
