### PR TITLE
Switched github plugin over to use bootstrap 3, removed bootstrap 2 depe...

### PR DESCRIPTION
**Pull request by philcryer**
...ndancies causing navbar conflicts, modified style of github tile display.

(this was caught and fixed by Chris Shafer: I fixed the bootstrap version conflict)

### CODE REVIEW

**Comment by philcryer** [comment]
merge to master was successful, tested the build, worked, pushed to gh-pages (prod) branch, worked. No downtime, predictable results

**Comment by ddgenome** [comment]
Why was this merged into master and not develop? Is someone going for fast-forward develop before these branches diverge?

**Comment by ddgenome** [comment]
I have synced up the develop and master branches. Please do the work in develop.

**Comment by philcryer** [comment]
he made his own branch, wasn't up on the work in develop branch. I went to merge and by def it went to master, should have merged it with develop, but then another PR to get it to master? Guess that's the workflow

**Pull request merged**
