### PR TITLE
simple spray part 2

### PR DESCRIPTION
**Pull request by samus42**
Part 2 of the Simple Spray app blog post, dealing with routes and responses.

### CODE REVIEW

**Comment by ddgenome** [comment]
@samus42 it looks like you haven't submitted the repo from this post, https://github.com/MonsantoCo/simple-spray-with-routing for open sourcing. See https://github.com/MonsantoCo/moseg/blob/master/ReleasingOpenSourceSoftware.md

Plus it would be good if the project had a README.md that pointed to the blog post.

**Comment by ddgenome** [comment]
Other than that, LGTM.

**Comment by ddgenome** [comment]
@slbahr please review

**Comment by slbahr** [comment]
Content approved!  Move forward Scott.

**Comment by samus42** [comment]
@ddgenome ok, i thought this process would cover both the blog and the example source code.  I'll get that part done.  In the past I've actually copied the blog post into the README.md but I can put a link to the blog instead once the blog post is published.

**Comment by slbahr** [comment]
@samus42 - Can you provide status or timeline?  Just want to make this is moving along or get a timeline for when this one can be completed.

**Comment by ddgenome** [comment]
@slbahr this is awaiting approval to open source the associated source code repository.

**Pull request merged**
