### PR TITLE
Post: Testing without mocking

### PR DESCRIPTION
**Pull request by jessitron**
This came out of a question that someone at SoundCloud asked me last week. It turned out to be a nice little microcosm of how to do this. I think the post will be useful both here and globally.

It needs some code formatting - I struggled with the html inside the code snippets. Like, it loses line breaks. Maybe @chrisshafer or @hibikir can help?

### CODE REVIEW

**Comment by jessitron** [comment]
added another section, based on experience Jorge and I had today

**Comment by jessitron** [comment]
Fixed the formatting: this one is ready for review and publish, editing also welcome

**Comment by ddgenome** [comment]
Looks good to me. @slbahr what say you?

**Comment by slbahr** [comment]
I like it but with one caveat....can we remove Facebook as the example?  My concern is referencing Facebook.  I have getting guidance from legal that we may want to refrain from these references.  I will work to get more clarification from legal on this but in the mean time can we make some type of generic reference?

**Comment by slbahr** [comment]
@jessitron and @ddgenome - Is this one ready to post?  Did we update the Facebook reference?

**Comment by jessitron** [comment]
removing the Facebook reference now. It's a lot of work, since I have to update three sets of example code.
And feels silly, since the code example isn't even ours. I was given it by SoundCloud :-/
but, it doesn't stop up from posting the information, so we can accommodate legal on this.

**Comment by jessitron** [comment]
See PR 37; I cleaned out the history too
https://github.com/MonsantoCo/engineering-blog/pull/37

**Comment by slbahr** [comment]
Thanks @jessitron !  I know it can be pain on those kinds of tweaks.  Until I get more clarification from legal and talk with them more about these kinds of things we have to play it safe.  BTW..I love the contributions you have had on these!  I am trying to push some others to contribute more too.  Any influence you have to get some people involved please lmk.

**Pull request closed without merging**
