### PR TITLE
Post on futures and implicits

### PR DESCRIPTION
**Pull request by hibikir**

### CODE REVIEW

**Comment by slbahr** [comment]
This looks good but I want Ryan Richt and / or David Dooling to weigh in from a technical perspective.

**Comment by slbahr** [comment]
Approved based on addtl approval by either David and/or Ryan

**Comment by ryan-richt** [comment]
There is much to say about futures elsewhere -> There is much said

**Comment by ryan-richt** [comment]
The second pair use -> The second pair uses

**Comment by ryan-richt** [comment]
This is procedural programming. ::: did you mean to say procedural or sequential?

**Comment by ryan-richt** [comment]
otherwise looks great to me! ship it!

**Pull request merged**
