### PR TITLE
move stax post from drafts to posts

### PR DESCRIPTION
**Pull request by ddgenome**
Kicking off the PR for the stax post by @philcryer .

I believe @slbahr has already approved it.

### CODE REVIEW

**Comment by slbahr** [comment]
Approved..I thought I had approved this some time ago but in reading it maybe not.  In any case, it is approved.

**Comment by slbahr** [comment]
Did this get posted?

**Comment by philcryer** [comment]
It did not, but it looks like it is all approved, @ddgenome - is there a reason this hasn't been pushed live yet? Thanks

**Comment by ddgenome** [comment]
You have not made the stax repo public yet

**Comment by philcryer** [comment]
Sorry, didn't know I had a task on this - so MonsantoCo/stax should be
public. Yes?

--
http://philcryer.com / 04A1 69CC A79F 7188
 
 
On Thu, Jul 2, 2015, at 01:45 PM, David Dooling wrote:
> You have not made the stax repo public yet


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/MonsantoCo/engineering-blog/pull/27#issuecomment-118122929

**Comment by slbahr** [comment]
Phil..One of the comments from ISO was asking that we make some type comment in regards to stating in the readme file concerning running this in 'root'.  The essence is that we want people to know that leverage this the potential risk and that normally you may not want to use this practice or that they should consider the security implications.  This is a case by case basis for someone to consider the risk.  This is not normally a Monsanto practice as security is our highest priority.  Please run your readme changes by @ddgenome , @ryan-richt , @strubie , @thofli and @cgill2 .  Can you update the readme file?

**Comment by philcryer** [comment]
Hi Stephanie, I'm not sure I follow, I never advise running services as the root user, and don't in the Stax readme or the blog post under review. My howtos have always focused on 'best practices' and running as root is a big no-no. Do you want us to explicitly say **DO NOT RUN THIS AS ROOT**, or ? If someone from ISO wants to chime in I'd be happy to hear what they're talking about. Security is very important to me as well. Thanks

**Comment by slbahr** [comment]
Thanks Phil for asking for clarification.  Maybe my memory is faulty but I had recalled this was the project with a concern with requiring this being run at root.  I will need the team to validate and if I am stating the wrong project, I apologize.   @strubie , @thofli and @cgill2 - Can you validate and contact Phil with more information.

**Comment by ddgenome** [comment]
@philcryer yes, stax was approved for open sourcing: https://github.com/MonsantoCo/moseg/issues/2

**Pull request merged**
