### PR TITLE
Bash stdin loop

### PR DESCRIPTION
**Pull request by ddgenome**
Adding another post on debugging bash/ssh

### CODE REVIEW

**Comment by slbahr** [comment]
Approved!

**Comment by ryan-richt** [comment]
Things are a bit more tricky if you only want <<<to>>> run a container on a subset of the instances.

**Comment by ddgenome** [comment]
Fixed, also changed "more tricky" to "trickier".

**Comment by ryan-richt** [comment]
I like it. Should the word "puzzler" appear in here anywhere? Seems like a potential on-going topic?

**Comment by ddgenome** [comment]
I changed a tag from "tutorials" to "puzzlers", but those tags do not seem to be rendered anywhere. Should we fix that @chris1492 ?

**Comment by ddgenome** [comment]
Inadvertently closed.

**Comment by ddgenome** [comment]
I'm going to merge this and post it. Dealing with the tags will be more involved.

**Comment by ryan-richt** [comment]
sweet

**Pull request merged**
