### PR TITLE
Seth's blog posts from LinkedIn

### PR DESCRIPTION
**Pull request by dr-seth**
Steph asked me to repost my linkedIn posts to the engineering blog

### CODE REVIEW

**Comment by ddgenome** [comment]
These look fine to me. @dr-seth would it be OK to change the dates a bit to ensure they are properly ordered on the blog?

**Comment by ddgenome** [comment]
@slbahr please review.

**Comment by dr-seth** [comment]
You can certainly change the dates and you can spread them out so they don't all go out at the same time

**Comment by slbahr** [comment]
The msging content is approved and agree on spacing out the publications.  The one caveat I have is the pictures....Are these Monsanto created did we obtain license to use them?

**Comment by dr-seth** [comment]
I created them by combining stock images.

**Comment by ddgenome** [comment]
Stock images with what licenses?

**Comment by slbahr** [comment]
We need to be careful about the image copyrights.  Recommendation, remove the images.  My concerns are:  We would need to validate the images are free AND that there is no issues with changing the images.  I would need to send this to our copyright team and would prefer avoiding that route if possible.  Thoughts @dr-seth

**Comment by dr-seth** [comment]
What ever you too think is the right thing to do

**Comment by ddgenome** [comment]
The first post is available: http://engineering.monsanto.com/2015/11/09/what-makes-a-data-scientist-part-1/

See https://github.com/MonsantoCo/engineering-blog/pull/58

**Comment by ddgenome** [comment]
This PR was split into three PRs, all of which are at least created. Closing.

**Pull request closed without merging**
