### PR TITLE
Post for CF-Metrics

### PR DESCRIPTION
**Pull request by mjseid**
Here's a post to go with the release of cf-metrics.  Please review, thanks

### CODE REVIEW

**Comment by slbahr** [comment]
Ok....I like the article but my concern is images of the other solutions.  Only due to copyright issues that I am learning more about.  So we can go one of two routes...1.)  give me a few days to investigate with the Copyright team or 2.) pull the images of those solutions from the article?  Thoughts?  I am going to move ahead and ask while you think about it because in either case I need to get legals opinion on it but will let you decide.  We still need @ddgenome and @ryan-richt review as well.

**Comment by mjseid** [comment]
Yeah, I would like to leave them b/c I think it looks better that way but just in case I have created a version without them.  Assuming david and ryan review, if we don't hear back from legal by thursday I'll swap to the non-logo version and proceed for logo-less this time.  Thanks

**Comment by mjseid** [comment]
OK, got tired of waiting.....  I've updated the date and the pic to remove all logo's, round two!

**Comment by ryan-richt** [comment]
Looks great to me!
 @slbahr I think we've been lead astray on copyright concerns, I think we should put them back and add a note the bottom that says Monsanto and this project are not affiliated with {list of the projects and companies backing those projects logos}. Commentary on someone else's work I think is fair use of copyrighted material.

**Pull request merged**
