### PR TITLE
re:Invent post

### PR DESCRIPTION
**Pull request by ddgenome**
Paging @ryan-richt , @markdsparks , and @djwilli3 . Let me know if this is OK with you.

@slbahr here is a post covering our talks at AWS re:Invent.

### CODE REVIEW

**Comment by ryan-richt** [comment]
LGTM thank you

Sent from my iPhone

On Oct 13, 2015, at 1:37 PM, David Dooling <notifications@github.com<mailto:notifications@github.com>> wrote:


Paging @ryan-richt<https://github.com/ryan-richt> , @markdsparks<https://github.com/markdsparks> , and @djwilli3<https://github.com/djwilli3> . Let me know if this is OK with you.

@slbahr<https://github.com/slbahr> here is a post covering our talks at AWS re:Invent.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MonsantoCo/engineering-blog/pull/50

Commit Summary

  *   re:Invent post

File Changes

  *   A _posts/2015-10-14-aws-reinvent.md<https://github.com/MonsantoCo/engineering-blog/pull/50/files#diff-0> (59)

Patch Links:

  *   https://github.com/MonsantoCo/engineering-blog/pull/50.patch
  *   https://github.com/MonsantoCo/engineering-blog/pull/50.diff

-
Reply to this email directly or view it on GitHub<https://github.com/MonsantoCo/engineering-blog/pull/50>.
This e-mail message may contain privileged and/or confidential information, and is intended to be received only by persons entitled
to receive such information. If you have received this e-mail in error, please notify the sender immediately. Please delete it and
all attachments from any servers, hard drives or any other media. Other use of this e-mail by you is strictly prohibited.

All e-mails and attachments sent and received are subject to monitoring, reading and archival by Monsanto, including its
subsidiaries. The recipient of this e-mail is solely responsible for checking for the presence of "Viruses" or other "Malware".
Monsanto, along with its subsidiaries, accepts no liability for any damage caused by any such code transmitted by or accompanying
this e-mail or any attachment.


The information contained in this email may be subject to the export control laws and regulations of the United States, potentially
including but not limited to the Export Administration Regulations (EAR) and sanctions regulations issued by the U.S. Department of
Treasury, Office of Foreign Asset Controls (OFAC).  As a recipient of this information you are obligated to comply with all
applicable U.S. export laws and regulations.

**Comment by markdsparks** [comment]
Looks good!  Thanks for putting this together.

**Comment by djwilli3** [comment]
Awesome!  Thanks david

**Comment by slbahr** [comment]
Approved..move forward.

**Pull request merged**
