### PR TITLE
Add blog entry for cf-users application

### PR DESCRIPTION
**Pull request by rlcaswmon**

### CODE REVIEW

**Comment by tj-corrigan** [comment]
We'll need to manually merge this post because of the history conflicts. @slbahr is this one ready to send to iso?

**Comment by rlcaswmon** [comment]
@tj-corrigan I merged this post so there are no longer conflicts.

**Comment by tj-corrigan** [comment]
I went and checked the history of your branch and still see some stuff that shouldn't be there. I wouldn't worry about it though, it is easy enough to just cherry-pick across your files.

**Comment by rlcaswmon** [comment]
@tj-corrigan Do you want to update the date on the blog post file?

**Comment by rlcaswmon** [comment]
@tj-corrigan I can do that if you want.

**Comment by tj-corrigan** [comment]
We still need approve from @slbahr and ISO before we will know the post date

**Comment by rlcaswmon** [comment]
@tj-corrigan  Any idea of what the status of this is?  Do you need anything else from me.

**Comment by slbahr** [comment]
Approved!

**Comment by tj-corrigan** [comment]
I went ahead and manually merged across since the history was still a bit tainted. Also updated the date and fixed a few typos. @rlcaswmon please delete your branch when you get a chance.

**Pull request closed without merging**
